import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('Seeding rich Ethiopian destinations, services, and events...');

  // Upsert or clear and re-create destinations
  await prisma.serviceInquiry.deleteMany({});
  await prisma.favorite.deleteMany({});
  await prisma.destination.deleteMany({});
  await prisma.service.deleteMany({});
  await prisma.eventItem.deleteMany({});

  await prisma.destination.createMany({
    data: [
      {
        id: 'd1',
        name: 'Lalibela',
        region: 'Amhara',
        blurb: 'Rock-hewn monolithic churches carved from volcanic tuff, an active holy pilgrimage site and 12th-century engineering miracle.',
        image: 'https://images.unsplash.com/photo-1523805009345-7448845a9e53?w=800',
        description: 'King Lalibela commissioned 11 monolithic rock-hewn churches in the 12th century to recreate a New Jerusalem in the rugged Lasta mountains of Ethiopia. Carved directly downward from red volcanic scoria into solid bedrock, these interconnected sanctuaries remain vibrant places of daily worship, incense-scented liturgical chant, and world-renowned UNESCO heritage.',
        bestTimeToVisit: 'October to March (Dry, sunny highlands; optimal for Genna Ethiopian Christmas on Jan 7 and Timkat Epiphany on Jan 19)',
        elevation: '2,500m (8,200 ft)',
        unescoStatus: true,
        rating: 4.95,
        highlights: 'Bet Giyorgis (Church of St. George carved in the shape of a cross),Bet Medhane Alem (largest monolithic rock church on Earth),Sacred ceremonial tunnels & underground passages,Meskel flower festival night vigils,Panoramic sunset hike to Asheten Maryam monastery',
        gettingThere: 'Daily scheduled Ethiopian Airlines flights from Addis Ababa Bole (ADD) to Lalibela Airport (LLI) (1 hour flight). Paved scenic airport shuttle takes 25 minutes to town center.',
      },
      {
        id: 'd2',
        name: 'Addis Ababa',
        region: 'Addis Ababa',
        blurb: "Ethiopia's vibrant capital — diplomatic heart of Africa, coffee birthplace culture, Entoto panoramic heights, and a fast-growing skyline.",
        image: 'https://images.unsplash.com/photo-1580746738099-72cbf9a7e315?w=800',
        description: 'Situated at the foot of Mount Entoto, Addis Ababa (meaning "New Flower") is the diplomatic capital of Africa, home to the African Union headquarters and UNECA. It bridges centuries-old coffee ceremonies with contemporary jazz clubs, bustling open-air markets like Mercato, and world-class museums housing humanity’s earliest ancestors.',
        bestTimeToVisit: 'Year-round (Highland climate with crisp evenings; dry season runs October through May with pleasant 23°C days)',
        elevation: '2,355m (7,726 ft)',
        unescoStatus: false,
        rating: 4.85,
        highlights: 'National Museum of Ethiopia (Lucy / Dinkinesh 3.2M-year-old fossil),Entoto Park with pine forest zip lines and city panoramas,Historic Tomoca Coffee and live Ethio-Jazz at Fendika,Addis Mercato (Africa’s largest open-air market),Unity Park & Grand Palace historic gardens',
        gettingThere: 'Global hub of Star Alliance carrier Ethiopian Airlines connecting 130+ international cities. Modern Light Rail and ride-hailing (Feres, Ride) operate across the city.',
      },
      {
        id: 'd3',
        name: 'Simien Mountains',
        region: 'Amhara',
        blurb: 'Dramatic precipices, jagged highland peaks, deep gorges, and endemic wildlife found nowhere else on earth.',
        image: 'https://images.unsplash.com/photo-1611348586804-61bf6c080437?w=800',
        description: 'The Simien Mountains National Park is often described as "The Chess Pieces of the Gods" — a dramatic plateau carved by millions of years of volcanic activity and erosion into dizzying vertical escarpments plunging 1,500 meters into valleys below. It is the sanctuary of the charismatic vegetarian Gelada monkeys, Walia Ibex, and the elusive Ethiopian Wolf.',
        bestTimeToVisit: 'Late September to November (Lush wildflower blooms & crisp clear skies) and December to March (Great trekking conditions)',
        elevation: '4,533m (Ras Dashen peak)',
        unescoStatus: true,
        rating: 4.92,
        highlights: 'Encounter wild troops of 200+ Gelada baboons up close,Trek to the summit of Ras Dashen (Ethiopia’s highest point at 4,533m),Gaze across the 500m sheer drop of Jinbar Waterfall,Spectacular sunsets over the Imet Gogo viewpoint,Sighting the rare Walia Ibex leaping along cliff edges',
        gettingThere: 'Fly from Addis to Gondar Airport (GDQ), followed by a scenic 2-hour 4WD drive via Debark Park headquarters.',
      },
      {
        id: 'd4',
        name: 'Harar Jugol',
        region: 'Harari',
        blurb: 'Ancient 16th-century walled Islamic city with 82 mosques, vibrant maze alleys, and century-old hyena feeding rituals.',
        image: 'https://images.unsplash.com/photo-1590402494587-44b71d7772f6?w=800',
        description: 'Considered the fourth holiest city in Islam, Harar Jugol is encircled by 4-meter-high stone walls built between the 13th and 16th centuries. Within its 368 narrow cobbled alleyways lie distinct traditional Harari homes, fragrant spice markets, and a unique historic coexistence between humans and wild spotted hyenas.',
        bestTimeToVisit: 'October to March (Warm, sunny days and cool pleasant evenings)',
        elevation: '1,885m (6,184 ft)',
        unescoStatus: true,
        rating: 4.89,
        highlights: 'Nightly wild hyena feeding ceremony outside the city gates,Arthur Rimbaud Cultural Center & Museum,Explore 82 mosques and 102 historic shrines inside the walls,Traditional Harari House architecture and woven basketry markets,Sampling world-famous Harar longberry specialty coffee',
        gettingThere: 'Fly from Addis Ababa to Dire Dawa (DIR) (50 min), followed by a 45-minute paved road drive to Harar.',
      },
    ],
  });

  await prisma.service.createMany({
    data: [
      {
        id: 's1',
        name: 'Addis Relocation Partners',
        category: 'Relocation',
        location: 'Addis Ababa',
        verified: true,
        blurb: 'End-to-end bespoke transition support for returning diaspora & foreign expats — luxury housing leases, Modjo port container customs, and paperwork.',
        image: 'https://images.unsplash.com/photo-1560184897-ae75f418493e?w=800',
        description: 'Addis Relocation Partners is Ethiopia’s premier expat and diaspora settlement agency. Founded by diaspora returnees with over 15 years of corporate relocation experience, we assist families and professionals with house hunting in secure Addis Ababa neighborhoods (Old Airport, Bole, CMC), vehicle customs clearance under diaspora duty-free schemes, school admissions, and utility setup.',
        phone: '+251 911 234 567',
        whatsapp: '+251911234567',
        email: 'contact@addisrelocation.com',
        address: 'Bole Medhanialem, Morning Star Mall 4th Floor, Addis Ababa',
        rating: 4.9,
        reviewCount: 142,
        operatingHours: 'Monday – Friday: 8:30 AM – 6:00 PM | Saturday: 9:00 AM – 1:00 PM',
        features: 'Expat neighborhood housing search,Modjo Dry Port container customs clearance,Yellow Card & Resident ID paperwork expediting,International school placement (ICS / Bingham / Sandford),Home furnishing and telecom eSIM provisioning',
      },
      {
        id: 's2',
        name: 'Habesha Legal Group',
        category: 'Legal services',
        location: 'Addis Ababa',
        verified: true,
        blurb: 'Licensed Ethiopian advocate firm specializing in diaspora property title validation, inheritance disputes, power of attorney, and commercial EIC licenses.',
        image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800',
        description: 'Habesha Legal Group is an elite full-service Ethiopian law office serving diaspora communities in the US, UK, Canada, and Europe. Our attorneys are admitted to practice before the Federal Supreme Court of Ethiopia. We ensure diaspora properties and real estate contracts are bulletproof, resolve land registry conflicts, draft certified Powers of Attorney (Wekilna), and navigate Ethiopian Investment Commission (EIC) commercial registrations.',
        phone: '+251 922 789 012',
        whatsapp: '+251922789012',
        email: 'info@habeshalegal.com',
        address: 'Kazanchis, Guinea Conakry St, Beside Radisson Blu, Addis Ababa',
        rating: 4.9,
        reviewCount: 98,
        operatingHours: 'Monday – Friday: 8:00 AM – 5:30 PM (EAT)',
        features: 'Real Estate contract & title deed (Sened) verification,Embassy certified Power of Attorney (Wekilna) handling,Ethiopian Investment Commission (EIC) business licensing,Inheritance law & family property dispute resolution,Forex banking & repatriation compliance counsel',
      },
      {
        id: 's3',
        name: 'Yene Guide Tours',
        category: 'Tour operators',
        location: 'Lalibela & Addis Ababa',
        verified: true,
        blurb: 'Boutique certified tour operator providing private 4WD Land Cruiser expeditions, historian guides, and luxury eco-lodge reservations across Ethiopia.',
        image: 'https://images.unsplash.com/photo-1500534623283-312aade485b7?w=800',
        description: 'Yene Guide Tours specializes in authentic, high-comfort journeys tailored for visiting diaspora families and international travelers. We provide modern Toyota Land Cruisers, certified English-speaking regional guides, private security logistics, and curated itineraries covering the Historic North Circuit, Danakil Depression, and Omo Valley cultural encounters.',
        phone: '+251 933 456 789',
        whatsapp: '+251933456789',
        email: 'adventures@yeneguide.com',
        address: 'Lalibela Main Road / Addis Ababa Bole Sub-city',
        rating: 4.8,
        reviewCount: 87,
        operatingHours: 'Daily: 7:00 AM – 8:00 PM (EAT)',
        features: 'Private V8/Land Cruiser vehicle rentals with vetted drivers,Licensed archaeological and historical guides,Domestic flight booking assistance with Ethiopian Airlines,Boutique eco-lodge & luxury hotel reservations,Custom family homecoming itineraries',
      },
      {
        id: 's4',
        name: 'Abyssinia Diaspora Wealth Advisors',
        category: 'Banking',
        location: 'Addis Ababa',
        verified: true,
        blurb: 'Advisory concierge for non-resident foreign currency (NRFC) diaspora accounts, treasury bonds, and commercial real estate financing in Ethiopia.',
        image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800',
        description: 'Specialized diaspora financial desk guiding Ethiopians living abroad through opening and operating Non-Resident Foreign Currency Accounts (USD, EUR, GBP) in Ethiopian commercial banks, buying government Diaspora Bonds, and securing mortgage loans for property developments in Addis Ababa.',
        phone: '+251 944 567 890',
        whatsapp: '+251944567890',
        email: 'diaspora@abyssiniawealth.et',
        address: 'Churchill Avenue, Financial District, Addis Ababa',
        rating: 4.9,
        reviewCount: 64,
        operatingHours: 'Monday – Friday: 8:30 AM – 5:00 PM',
        features: 'Diaspora USD/EUR/GBP foreign currency account opening,Diaspora mortgage & housing financing guidance,Official remittance channel rate guidance,National Bank of Ethiopia foreign exchange compliance,Treasury bills and government infrastructure bonds',
      },
    ],
  });

  await prisma.eventRsvp.deleteMany({});
  await prisma.eventItem.deleteMany({});

  await prisma.eventItem.createMany({
    data: [
      {
        id: 'e1',
        title: 'Meskel Festival UNESCO Gathering',
        date: new Date('2026-09-27T15:00:00.000Z'),
        time: '03:30 PM – 09:30 PM EAT',
        city: 'Addis Ababa',
        venue: 'Meskel Square & Dembel Amphitheater',
        category: 'Culture',
        price: 'Free Public Admission (VIP Grandstand 1,200 ETB)',
        organizer: 'Ethiopian Orthodox Tewahedo Church & Ministry of Tourism',
        blurb: 'The legendary eve of Meskel celebration with the monumental Demera bonfire, choral hymns, and traditional processions.',
        description: 'Meskel is one of Ethiopia’s most breathtaking religious and cultural celebrations, inscribed on UNESCO’s Representative List of the Intangible Cultural Heritage of Humanity. Hundreds of thousands of priests, deacons in gold-embroidered velvet robes, Sunday school youth choir groups, and international visitors gather at Meskel Square to light the massive ceremonial Demera bonfire. Experience sacred songs, joyful ululations, and the evening glow of thousands of beeswax candles.',
        agenda: '03:30 PM: Gates open for VIP grandstand & international visitors,04:30 PM: Ceremonial procession of Patriarch and High Bishops,05:45 PM: Choral canticles and traditional liturgical hymns,06:30 PM: Ceremonial lighting of the Demera bonfire,07:30 PM: Evening singing & community cultural festivities',
        capacity: 100000,
        verified: true,
        image: 'https://images.unsplash.com/photo-1541532713592-79a0317b6b77?w=800',
      },
      {
        id: 'e2',
        title: 'Addis Diaspora Tech & AI Summit 2026',
        date: new Date('2026-10-18T06:00:00.000Z'),
        time: '09:00 AM – 06:30 PM EAT',
        city: 'Addis Ababa',
        venue: 'Ethiopian Skylight Hotel Grand Ballroom, Bole',
        category: 'Business',
        price: 'Early Bird $45 USD / 3,500 ETB',
        organizer: 'Addis Tech Hub & Diaspora Innovation Network',
        blurb: 'Bringing together global diaspora tech leaders, venture founders, and local engineers building Africa’s digital future.',
        description: 'The premier diaspora technology conference in East Africa. Connect with diaspora software executives from Silicon Valley, London, and Berlin alongside founders of top Ethiopian fintech, agritech, and AI startups. Features keynote presentations on cross-border payments, cloud architecture in emerging markets, startup pitch competitions with angel investors, and high-impact recruiting opportunities.',
        agenda: '09:00 AM: Breakfast & registration networking,10:00 AM: Keynote — Leapfrogging AI & Digital Payments in Ethiopia,11:30 AM: Panel — Returning Home: Diaspora Founders Playbook,01:00 PM: Networking executive buffet lunch,02:30 PM: Seed-Stage Startup Pitch Competition,04:30 PM: 1-on-1 Investor & Engineer Matchmaking Lounge,05:30 PM: Rooftop Sunset Cocktail Reception',
        capacity: 850,
        verified: true,
        image: 'https://images.unsplash.com/photo-1511578314322-379afb476865?w=800',
      },
      {
        id: 'e3',
        title: 'Great Ethiopian Run International 10K',
        date: new Date('2026-11-22T04:30:00.000Z'),
        time: '07:30 AM – 12:30 PM EAT',
        city: 'Addis Ababa',
        venue: 'Meskel Square Start/Finish Line',
        category: 'Festival',
        price: 'Diaspora / International Runner $90 USD',
        organizer: 'Great Ethiopian Run Ltd & Haile Gebrselassie Foundation',
        blurb: 'Africa’s biggest, most vibrant road race with 45,000 runners, elite athletes, music stages, and carnival street energy.',
        description: 'Founded by legendary Olympic champion Haile Gebrselassie, the Great Ethiopian Run 10km is renowned as the happiest, most energetic road race in the world. Running at 2,400 meters above sea level alongside thousands of Ethiopians in matching event t-shirts, you will experience live traditional music bands at every kilometer, high-altitude athletic thrills, and unmatched community camaraderie.',
        agenda: '06:30 AM: Bag drop & warm-up with national athletics champions,07:30 AM: Wave 1 — Elite & international wave start,07:45 AM: Wave 2 — Diaspora & charity participants start,10:00 AM: Medals presentation & Haile Gebrselassie speech,11:00 AM: Post-race cultural street concert & recovery brunch',
        capacity: 45000,
        verified: true,
        image: 'https://images.unsplash.com/photo-1530549387789-4c1017266635?w=800',
      },
      {
        id: 'e4',
        title: 'Ethiopian Specialty Coffee Cupping & Export Expo',
        date: new Date('2026-12-05T06:30:00.000Z'),
        time: '09:30 AM – 05:00 PM EAT',
        city: 'Addis Ababa',
        venue: 'Millennium Hall, Bole Medhanialem',
        category: 'Business',
        price: 'General Badge 1,500 ETB / Trade Buyer $60 USD',
        organizer: 'Ethiopian Coffee and Tea Authority & Specialty Coffee Guild',
        blurb: 'Direct trade cuppings, auction microlots, and masterclasses from Yirgacheffe, Sidama, Guji, and Harrar farm producers.',
        description: 'Immerse yourself in the birthplace of Arabica coffee. This 3-day expo brings together commercial producers, specialty washing station operators, international green buyers, and diaspora coffee entrepreneurs. Taste the world’s most coveted high-scoring microlots, participate in Q-grader guided cupping tables, and establish direct-trade export relationships.',
        agenda: '09:30 AM: Exhibition hall ribbon cutting & keynote,11:00 AM: Guided Cupping Session 1 — Yirgacheffe & Guji Anaerobic Naturals,01:30 PM: Workshop — Export Logistics, LC Financing & NBE Directives,03:00 PM: Guided Cupping Session 2 — Kaffa & Limu Forest-Grown Washed,04:30 PM: Direct-Trade Buyer & Grower Signing Ceremony',
        capacity: 3200,
        verified: true,
        image: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=800',
      },
      {
        id: 'e5',
        title: 'Diaspora Homecoming Gala & Networking Night',
        date: new Date('2026-12-28T16:00:00.000Z'),
        time: '07:00 PM – 11:30 PM EAT',
        city: 'Addis Ababa',
        venue: 'Sheraton Addis Luxury Collection Hotel, Lalibela Grand Ballroom',
        category: 'Networking',
        price: 'Individual Ticket 4,500 ETB / $65 USD',
        organizer: 'Ethiopian Diaspora Trust Fund & DALEEL Community',
        blurb: 'An elegant black-tie evening celebrating diaspora impact, cultural performances, gourmet Ethiopian fusion dinner, and networking.',
        description: 'The signature social event of the December diaspora homecoming season. Connect with fellow diaspora professionals, entrepreneurs, returning families, and cultural leaders in an exquisite evening featuring world-class Ethiopian jazz fusion by Ethio-jazz masters, an artisan textile showcase, a five-course culinary celebration, and inspirational diaspora achievement awards.',
        agenda: '07:00 PM: Red carpet welcome & Tej wine cocktail hour,08:00 PM: Opening remarks & Diaspora Changemakers Awards,08:45 PM: Five-course gourmet Ethiopian banquet dinner,09:45 PM: Live Ethio-Jazz performance & cultural dance ensemble,10:30 PM: Networking dessert lounge & closing champagne toast',
        capacity: 500,
        verified: true,
        image: 'https://images.unsplash.com/photo-1519671482749-fd09be7ccebf?w=800',
      },
    ],
  });


  await prisma.investmentInquiry.deleteMany({});
  await prisma.investmentOpportunity.deleteMany({});

  await prisma.investmentOpportunity.createMany({
    data: [
      {
        id: 'inv1',
        title: 'Bole Atlas SkyLine Luxury Residences',
        sector: 'Real Estate',
        location: 'Bole Atlas, Addis Ababa',
        minInvestment: 45000,
        currency: 'USD',
        expectedReturn: '18% – 22% Annual ROI',
        investmentModel: 'Direct Ownership / Off-Plan Fractional',
        timeline: 'Q4 2027 Delivery',
        verified: true,
        blurb: 'Prime 24-story residential development in diplomat corridor with guaranteed rental yield and diaspora mortgage options.',
        image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800',
        description: 'Bole Atlas SkyLine Residences offers diaspora investors a turnkey entry point into Addis Ababa’s most prestigious residential real estate market. Positioned 8 minutes from Bole International Airport, the development features luxury finishes, 24/7 backup dual generators, panoramic rooftop pools, and an institutional property management service ensuring foreign-currency rental income from embassy and NGO tenants.',
        highlights: 'Prime diplomat & UN residential zone,Guaranteed 12% USD rental yield for first 3 years,Title deed issued in foreign citizen / yellow card holder name,Dedicated diaspora property concierge with escrow bank protection,Underground parking & private health club',
        incentives: 'Full foreign-currency remittance back to overseas accounts under NBE Directive,0% capital gains tax on primary diaspora residences,Duty-free furniture & fixture importation voucher',
        contactEmail: 'realestate@daleel.et',
        contactPhone: '+251 911 200 440',
        status: 'open',
      },
      {
        id: 'inv2',
        title: 'Rift Valley Organic Hass Avocado & Export Farm',
        sector: 'Agriculture',
        location: 'Hawassa / Sidama Region',
        minInvestment: 25000,
        currency: 'USD',
        expectedReturn: '24% – 28% Target IRR',
        investmentModel: 'Equity Syndicate / Profit Share',
        timeline: 'Immediate Cash Flow (Year 2 Harvest)',
        verified: true,
        blurb: '120-hectare commercial Hass avocado and high-altitude export orchard with pre-signed off-take contracts to European markets.',
        image: 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=800',
        description: 'Capitalizing on Ethiopia’s natural microclimate and rich volcanic soils, this commercial agribusiness operates an advanced drip-irrigated Hass avocado enterprise. Certified by GlobalG.A.P. and SMETA, the project exports fresh produce via Ethiopian Cargo cold-chain logistics to Rotterdam and Dubai.',
        highlights: 'Pre-signed 7-year European supermarket export purchase agreements,Equipped with drip irrigation and solar water pumps,500+ local farming family cooperatives supported,Cold-chain facility within 35 minutes of Hawassa Airport',
        incentives: '5-year corporate income tax holiday approved by Ethiopian Investment Commission,100% duty-free import on agricultural machinery, fertilizers & cold-storage trucks,Access to subsidized state agricultural leasehold land at preferential rates',
        contactEmail: 'agri@daleel.et',
        contactPhone: '+251 922 344 550',
        status: 'open',
      },
      {
        id: 'inv3',
        title: 'FinPay Ethiopia — Unified Diaspora Remittance Gateway',
        sector: 'Technology',
        location: 'Addis Ababa ICT Park',
        minInvestment: 15000,
        currency: 'USD',
        expectedReturn: '30% – 35% Projected 3-Yr IRR',
        investmentModel: 'SAFE Note / Convertible Seed Round',
        timeline: 'Pre-Series A Open',
        verified: true,
        blurb: 'National Bank of Ethiopia-licensed payment switch enabling zero-fee instant cross-border remittances and merchant checkout.',
        image: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=800',
        description: 'FinPay is revolutionizing the $5B+ annual Ethiopian remittance flow. By bridging international cards (Visa/Mastercard/Apple Pay) with Telebirr and local Ethiopian bank accounts, FinPay cuts diaspora transaction fees by 60% while providing real-time exchange rates compliant with national foreign exchange directives.',
        highlights: 'NBE Payment System Operator (PSO) regulatory sandbox graduate,Processed $18M in annualized pilot remittance volume,API integration with 6 top commercial banks & Telebirr,Backed by prominent Silicon Valley and Ethiopian diaspora angel syndicates',
        incentives: 'Addis Ababa ICT Park tenant status with subsidized high-speed fiber & office space,Intellectual Property tax relief under the Startup Ethiopia Proclamation,Special foreign investor visa facilitation for diaspora founders and key personnel',
        contactEmail: 'tech@daleel.et',
        contactPhone: '+251 933 455 660',
        status: 'open',
      },
      {
        id: 'inv4',
        title: 'Awash Basin Solar Energy Grid Project (20MW)',
        sector: 'Energy',
        location: 'Awash, Afar / Oromia Corridor',
        minInvestment: 50000,
        currency: 'USD',
        expectedReturn: '14% – 16% Fixed Annual Yield',
        investmentModel: 'Infrastructure Debt / Revenue Participation',
        timeline: 'Commercial Operation Q1 2027',
        verified: true,
        blurb: 'Grid-scale utility solar plant supplying clean power to surrounding industrial parks with government-backed Power Purchase Agreement.',
        image: 'https://images.unsplash.com/photo-1509391365360-2e959784a276?w=800',
        description: 'A 20MW utility-scale solar photovoltaic project developed under the Ethiopian Public-Private Partnership (PPP) framework. Strategically located along the high-irradiance Awash economic corridor, the facility directly feeds the national grid with guaranteed off-take by Ethiopian Electric Power (EEP).',
        highlights: '20-year sovereign-backed Power Purchase Agreement (PPA) with EEP,Independent Power Producer (IPP) legal framework with MIGA political risk coverage,Supplies power to over 40,000 households and 3 industrial parks,Tier-1 bifacial solar panels and smart tracker technology',
        incentives: '10-year income tax exemption for renewable energy infrastructure investments,Full exemption from customs duties and withholding taxes on imported solar equipment,Guaranteed foreign currency repatriation priority for sovereign infrastructure debt',
        contactEmail: 'energy@daleel.et',
        contactPhone: '+251 944 566 770',
        status: 'open',
      },
      {
        id: 'inv5',
        title: 'Dire Dawa Free Trade Zone Apparel & Textiles Hub',
        sector: 'Manufacturing',
        location: 'Dire Dawa Free Trade Zone',
        minInvestment: 30000,
        currency: 'USD',
        expectedReturn: '20% – 24% Projected ROI',
        investmentModel: 'Joint Venture / Preferred Equity',
        timeline: 'Factory Shell Complete / Fitout Stage',
        verified: true,
        blurb: 'Export-oriented garment and cotton textile manufacturing facility connecting directly to Djibouti Port via the Ethio-Djibouti Railway.',
        image: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800',
        description: 'Leveraging Ethiopia’s Africa Continental Free Trade Area (AfCFTA) access and competitive renewable hydroelectric power, this modern garment facility specializes in sustainable organic cotton apparel for European and regional African retailers.',
        highlights: 'Located inside Ethiopia’s premier Free Trade Zone with zero customs inspection delays,Direct rail siding connects factory floor to Port of Djibouti in under 12 hours,Access to 100% renewable hydropower at world-competitive rates,Targeting 1,200 direct jobs for youth and women in the region',
        incentives: 'Indefinite exemption from all customs duties on raw materials, components & machinery,8-year tax holiday with zero corporate income tax,Foreign currency retention accounts allowing 100% export revenue retention',
        contactEmail: 'manufacturing@daleel.et',
        contactPhone: '+251 955 677 880',
        status: 'open',
      },
    ],
  });

  await prisma.productOrderInquiry.deleteMany({});
  await prisma.product.deleteMany({});

  await prisma.product.createMany({
    data: [
      {
        id: 'prod1',
        title: 'Royal Tibeb Handwoven Habesha Kemis',
        price: 14500,
        currency: 'ETB',
        category: 'Fashion & Textiles',
        sellerName: 'Sabahar Artisan Weaving Guild',
        sellerVerified: true,
        sellerLocation: 'Shiro Meda & Bole, Addis Ababa',
        sellerPhone: '+251 911 300 210',
        sellerWhatsapp: '+251911300210',
        image: 'https://images.unsplash.com/photo-1594223274512-ad4803739b7c?w=800',
        images: 'https://images.unsplash.com/photo-1594223274512-ad4803739b7c?w=800,https://images.unsplash.com/photo-1509631179647-0177331693ae?w=800',
        blurb: 'Exquisite custom-tailored Habesha Kemis with authentic hand-woven golden Tibeb embroidery and sheer Netela shawl.',
        description: 'Meticulously crafted over 18 days by master weavers in Shiro Meda using 100% fine Ethiopian handspun cotton (Fetel). Adorned with intricate royal golden Tibeb borders along the neckline, cuffs, and hem. Includes a double-layered sheer matching Netela with symmetrical gold thread edging. Perfect for diaspora weddings, holiday gatherings, and cultural milestones.',
        materials: '100% Ethiopian Handspun Cotton (Fetel), Pure Silk & Gold Zari Thread Embroidery',
        origin: 'Addis Ababa (Shiro Meda Artisan Quarter)',
        inStock: true,
        status: 'active',
      },
      {
        id: 'prod2',
        title: 'Single-Origin Guji Anaerobic Specialty Beans (1kg)',
        price: 3800,
        currency: 'ETB',
        category: 'Specialty Coffee',
        sellerName: 'Bonga Highland Micro-Roasters',
        sellerVerified: true,
        sellerLocation: 'Bole Medhanialem, Addis Ababa',
        sellerPhone: '+251 922 440 320',
        sellerWhatsapp: '+251922440320',
        image: 'https://images.unsplash.com/photo-1559525839-b184a4d698c7?w=800',
        images: 'https://images.unsplash.com/photo-1559525839-b184a4d698c7?w=800,https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=800',
        blurb: 'SCA 89.5 Cup Score Grade 1 heirloom Arabica micro-lot with bursting notes of jasmine, ripe blueberry, and candied peach.',
        description: 'Grown at 2,150 meters altitude in the fertile volcanic red soils of the Guji zone. This microlot underwent 96 hours of controlled anaerobic carbon maceration fermentation before slow drying on raised African beds for 21 days. Roasted fresh weekly in small batches in Addis Ababa. Comes nitrogen-sealed in a resealable one-way degassing valve pouch, making it ideal for international travel or diaspora delivery.',
        materials: '100% Heirloom Arabica Beans (Whole Bean), Anaerobic Natural Process',
        origin: 'Uraga, Guji Zone, Oromia (2,150m)',
        inStock: true,
        status: 'active',
      },
      {
        id: 'prod3',
        title: 'Heritage Full-Grain Ethiopian Leather Weekender Duffle',
        price: 18500,
        currency: 'ETB',
        category: 'Leather Goods',
        sellerName: 'Benshalom Master Leatherworks',
        sellerVerified: true,
        sellerLocation: 'Kazanchis, Addis Ababa',
        sellerPhone: '+251 933 550 430',
        sellerWhatsapp: '+251933550430',
        image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800',
        images: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800,https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800',
        blurb: 'Handcrafted luxury travel duffle fashioned from world-renowned highland calf leather with antique brass hardware.',
        description: 'Ethiopia is world-famous for its supple, dense-grain highland calf and sheep leather. This heirloom weekender bag is vegetable-tanned with mimosa bark extract without harsh synthetic dyes, creating a rich chestnut patina that deepens with age. Features reinforced double-stitched leather handles, an adjustable padded shoulder strap, an interior laptop compartment, and compliant carry-on cabin dimensions for Ethiopian Airlines flights.',
        materials: 'Full-Grain Vegetable-Tanned Ethiopian Calfskin, Solid Antique Brass YKK Zippers',
        origin: 'Bishoftu Tannery & Addis Ababa Workshop',
        inStock: true,
        status: 'active',
      },
      {
        id: 'prod4',
        title: 'Hand-Carved Lalibela Processional Cross (Brass & Walnut)',
        price: 8200,
        currency: 'ETB',
        category: 'Art & Crafts',
        sellerName: 'Roha Heritage Artisans',
        sellerVerified: true,
        sellerLocation: 'Lalibela & Piassa, Addis Ababa',
        sellerPhone: '+251 944 660 540',
        sellerWhatsapp: '+251944660540',
        image: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=800',
        images: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=800',
        blurb: 'Authentic 12th-century Lalibela cross pattern cast in golden brass using the traditional lost-wax method on a polished walnut stand.',
        description: 'Handcrafted by third-generation metalworkers tracing their lineage to the sacred rock-hewn church craftsmen of Roha (Lalibela). Each cross is individually cast in solid brass using ancestral lost-wax molds, then hand-engraved with complex geometric lattice knotwork symbolizing eternal life and heavenly harmony. Mounted upon an Ethiopian highland walnut base for desk or mantelpiece display.',
        materials: 'Solid Cast Ethiopian Brass, Hand-Carved Highland Olive/Walnut Wood Base',
        origin: 'Lalibela, Amhara Region',
        inStock: true,
        status: 'active',
      },
      {
        id: 'prod5',
        title: 'Traditional Clay Jebena Coffee Ceremony Set (12-Piece)',
        price: 4200,
        currency: 'ETB',
        category: 'Art & Crafts',
        sellerName: 'Oromia Clay Pottery Masters Guild',
        sellerVerified: true,
        sellerLocation: 'Addis Ababa & Bishoftu',
        sellerPhone: '+251 955 770 650',
        sellerWhatsapp: '+251955770650',
        image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800',
        images: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800',
        blurb: 'Authentic pit-fired black clay Jebena pot, traditional woven straw ring, incense burner (Girgira), and 6 porcelain Sini cups.',
        description: 'Bring the sacred ritual of the Ethiopian coffee ceremony (Buna Tetu) to your home abroad or local residence. Includes a hand-burnished black clay Jebena with curved spout, woven straw placement ring (Mekedem), a ceramic incense burner for Frankincense and Myrrh, and 6 porcelain handle-less Sini cups with golden Ethiopian flag filigree.',
        materials: 'Natural River Clay (Pit-Fired & Smoked), Woven Straw Ring, Glazed Ceramic',
        origin: 'Bishoftu & Woliso, Ethiopia',
        inStock: true,
        status: 'active',
      },
      {
        id: 'prod6',
        title: 'Axum Silver Filigree Telsem Pendant with Ethiopian Opal',
        price: 12800,
        currency: 'ETB',
        category: 'Jewelry',
        sellerName: 'Axum Master Goldsmith Collective',
        sellerVerified: true,
        sellerLocation: 'Piassa Gold Market, Addis Ababa',
        sellerPhone: '+251 966 880 760',
        sellerWhatsapp: '+251966880760',
        image: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=800',
        images: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=800',
        blurb: '925 sterling silver filigree medallion featuring an authenticated natural glowing Welo rainbow opal gemstone.',
        description: 'An extraordinary union of ancient Axumite Telsem protective talismanic motifs and Ethiopia’s celebrated Welo precious opals. Hand-soldered fine silver wire filigree encases a natural 2.5-carat untreated crystal opal exhibiting fiery green, orange, and golden play-of-color. Includes an authenticated jeweler certificate of gemstone origin and an 18-inch sterling silver chain.',
        materials: '925 Solid Sterling Silver, 2.5ct Natural Untreated Ethiopian Welo Opal',
        origin: 'Axum & Delanta, Welo, Ethiopia',
        inStock: true,
        status: 'active',
      },
    ],
  });

  console.log('✅ Seed completed successfully with rich Ethiopian data.');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
